# Generated by Django 2.0.2 on 2018-06-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_auto_20180626_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
