# Generated by Django 2.0.2 on 2018-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0009_auto_20180703_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='', upload_to='shopApp/static/img'),
        ),
    ]
