# Generated by Django 2.0.2 on 2018-07-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0010_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='make',
            field=models.CharField(default='', max_length=200),
        ),
    ]
