# Generated by Django 2.0.2 on 2018-07-23 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopApp', '0011_item_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('language', models.CharField(choices=[('FI', 'Finnish'), ('EN', 'English')], max_length=2)),
                ('refunds_left', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='ad_1',
            field=models.ImageField(default='', upload_to='shopApp/static/img'),
        ),
        migrations.AddField(
            model_name='category',
            name='ad_2',
            field=models.ImageField(default='', upload_to='shopApp/static/img'),
        ),
    ]
