# Generated by Django 2.0.2 on 2018-07-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0014_auto_20180723_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ad_1',
            field=models.ImageField(default='', upload_to='shopApp/static/img'),
        ),
        migrations.AddField(
            model_name='category',
            name='ad_2',
            field=models.ImageField(default='', upload_to='shopApp/static/img'),
        ),
    ]
