# Generated by Django 2.0.2 on 2018-07-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0015_auto_20180723_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
