# Generated by Django 2.0.2 on 2018-07-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0018_auto_20180723_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
