# Generated by Django 2.0.2 on 2018-08-01 14:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0026_review_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reviews',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, unique=True), blank=True, default=[], size=50),
        ),
    ]
