# Generated by Django 2.0.2 on 2018-08-01 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0027_item_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
