# Generated by Django 2.0.2 on 2018-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0028_auto_20180801_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
