# Generated by Django 2.0.2 on 2018-08-07 15:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0034_auto_20180807_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='properties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=500), blank=True, default=[], size=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
