# Generated by Django 2.0.2 on 2018-08-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0035_auto_20180807_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
