# Generated by Django 2.0.2 on 2018-08-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0037_remove_review_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
