# Generated by Django 2.0.2 on 2018-08-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0039_auto_20180810_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
