# Generated by Django 2.0.2 on 2018-08-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0040_auto_20180811_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
