# Generated by Django 2.0.2 on 2018-08-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0041_item_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category_name',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(db_column='category_name', on_delete=django.db.models.deletion.CASCADE, to='shopApp.Category'),
        ),
    ]
