# Generated by Django 2.0.2 on 2018-08-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0044_auto_20180821_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
