# Generated by Django 2.0.2 on 2018-08-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0045_auto_20180823_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateTimeField(verbose_name='date of order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.Item')),
                ('profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.Profile')),
            ],
        ),
    ]
