# Generated by Django 2.0.2 on 2018-08-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0046_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_of_order',
        ),
    ]
