# Generated by Django 2.0.2 on 2018-09-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0054_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
